import Aura from "@primeuix/themes/aura";

export const CONFIG = {
  locale: {
    accept: "Aceptar",
    reject: "Cancelar",
    choose: "Elegir",
    upload: "Subir",
    cancel: "Cancelar",
    dayNames: [
      "Domingo",
      "Lunes",
      "Martes",
      "Miércoles",
      "Jueves",
      "Viernes",
      "Sábado",
    ],
    dayNamesShort: ["Dom", "Lun", "Mar", "Mié", "Jue", "Vie", "Sáb"],
    dayNamesMin: ["Dom", "Lun", "Mar", "Mie", "Jue", "Vie", "Sab"],
    monthNames: [
      "Enero",
      "Febrero",
      "Marzo",
      "Abril",
      "Mayo",
      "Junio",
      "Julio",
      "Agosto",
      "Septiembre",
      "Octubre",
      "Noviembre",
      "Diciembre",
    ],
    monthNamesShort: [
      "Ene",
      "Feb",
      "Mar",
      "Abr",
      "May",
      "Jun",
      "Jul",
      "Ago",
      "Sep",
      "Oct",
      "Nov",
      "Dic",
    ],
    today: "Hoy",
    weekHeader: "Sm",
    firstDayOfWeek: 1,
    dateFormat: "dd/mm/yy",
    emptyFilterMessage: "No se encontraron resultados",
    emptyMessage: "No hay opciones disponibles",
    startsWith: "Empieza con",
    contains: "Contiene",
    notContains: "No contiene",
    endsWith: "Termina con",
    equals: "Igual a",
    notEquals: "Distinto de",
    noFilter: "Sin filtro",
    lt: "Menor que",
    lte: "Menor o igual que",
    gt: "Mayor que",
    gte: "Mayor o igual que",
    dateIs: "Fecha igual",
    dateIsNot: "Fecha distinta",
    dateBefore: "Fecha antes",
    dateAfter: "Fecha después",
    clear: "Limpiar",
    apply: "Aplicar",
    matchAll: "Coincidir todo",
    matchAny: "Coincidir alguno",
  },
  theme: {
    preset: Aura,
    options: {
      darkModeSelector: false,
      // cssLayer: {
      //     name: "primevue",
      //     order: "theme, base, primevue",
      // },
    },
  },
};
